FROM elixir:1.4

RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /opt/happytodo

ENV MIX_ENV=prod

RUN mkdir config
COPY config/* config/
COPY mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

COPY . .

RUN mix release --env=prod --verbose
